/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/ground-palm.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function GroundPalm(props) {
  const { nodes, materials } = useGLTF('/models/ground-palm.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0,0,0]} scale={0.2}>
        <mesh geometry={nodes.PaperTreesMesh017.geometry} material={materials['Paper Trees Leaves']} />
        <mesh geometry={nodes.PaperTreesMesh017_1.geometry} material={materials['Paper Trees Stem']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/ground-palm.glb')
