/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/palm.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Palm(props) {
  const { nodes, materials } = useGLTF('../../../public/models/palm.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0,1,0]} scale={0.2}>
        <mesh geometry={nodes.PaperTreesMesh034.geometry} material={materials['Paper Trees Leaves']} />
        <mesh geometry={nodes.PaperTreesMesh034_1.geometry} material={materials['Paper Trees Stem']} />
      </group>
    </group>
  )
}

useGLTF.preload('../../../public/models/palm.glb')
